### ISSUE TITLE
Version for AWS (Amazon Web Services)

### ISSUE THREAD

**Issue by ghost** [lnklnklnk/ga-bq#17]
I was just wondering why it was based on Google Cloud? and how difficult it would be to add a version compatible with Amazon Web Services?

**Comment by marchenko1985** [comment]
@MarcoPorracin you definitely can, But, think about following, incoming traffic is free in both cloud providers, but outgoing is paid. When you are inside google cloud it is ok, you do not have outgoing traffic, but in case AWS you will be streaming batch inserts into BigQuery (which are free) but you will be charged from AWS for outgoing traffic.

So the question is it worth it? (Personally I do not like GAE, but there is Google DataFlow which is designed for such kind of tasks)

Hope it helps, because this project easily can be implemented in AWS Labmda + SQS but there should be reason why people not doing it that way

**Comment by ghost** [comment]
@mac2000 
When i posted this i mean going full on AWS. You are thinking in BigQuery and im talking about doing everything inside Amazon, EC2 + MongoDB + Any other service you might need to host the app. 
And if the question is why? 
Just because all the DDBB in AWS and im more familiarized with the platform.
